language: c

compiler:

  - gcc

before_install:

  - sudo apt-get update
  
  - sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev
  
install:

 - echo "Reached install section"
  
script:

  - echo "Reached Script Section"
 # - gcc hello_world.c -o output
 # - ./output  

 # - echo "compiling single_sample_A.c"
 # - gcc single_sample_A.c -o learn_J -lpthread
 ## - gcc single_sample_A.c -o learn_J -lpthread
 # - ./learn_J
  
  - echo "compiling JJ_practice.c"
  - gcc JJ_practice.c -o output_JJ -lpthread
  - ./output_JJ

